# Generated by Django 4.1.2 on 2022-12-11 16:09

from django.db import migrations, models
import django.db.models.deletion
import member.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('leader', models.CharField(max_length=255)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='HomeCell',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('leader', models.CharField(max_length=255)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('other_names', models.CharField(blank=True, max_length=255, null=True, verbose_name='Other Names')),
                ('active', models.BooleanField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('discipler', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('state_of_origin', models.CharField(blank=True, max_length=255, null=True)),
                ('lga', models.CharField(blank=True, max_length=255, null=True, verbose_name='Local Governemnt Area')),
                ('marital_status', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed')], default='S', max_length=1)),
                ('spouse_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Spouse Name (Leave Blank if Single)')),
                ('next_of_kin', models.CharField(blank=True, max_length=255, null=True, verbose_name='Next of Kin')),
                ('relationship_with_nok', models.CharField(blank=True, max_length=255, null=True, verbose_name='Relationship with Next of Kin')),
                ('number_of_children', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of children')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Residential Address')),
                ('date_joined', models.DateField(blank=True, null=True)),
                ('tribe', models.CharField(blank=True, max_length=255, null=True)),
                ('fathers_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mothers_name', models.CharField(blank=True, max_length=255, null=True)),
                ('guardians_name', models.CharField(blank=True, max_length=255, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=member.models.upload_image_path)),
                ('signature', models.ImageField(blank=True, null=True, upload_to=member.models.upload_image_path)),
                ('home_cell', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='member.homecell')),
            ],
        ),
        migrations.CreateModel(
            name='SubGroup',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('leader', models.CharField(max_length=255)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='TestDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='MemberSubGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to='member.member')),
                ('subgroup', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to='member.subgroup')),
            ],
        ),
        migrations.CreateModel(
            name='MemberCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='member.committee')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='member.member')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentDetails',
            fields=[
                ('employer_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('office_address', models.CharField(blank=True, max_length=255, null=True)),
                ('years_in_employment', models.PositiveIntegerField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='member.member')),
            ],
        ),
        migrations.CreateModel(
            name='EducationInformation',
            fields=[
                ('school', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('course', models.CharField(blank=True, max_length=255, null=True)),
                ('start_year', models.PositiveIntegerField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='member.member')),
            ],
        ),
    ]
