# Generated by Django 4.0.5 on 2022-12-16 04:51

from django.db import migrations, models
import member.models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_membership_email_alter_membership_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='signature',
            field=models.ImageField(blank=True, default='static\x07ssets\\img\\images\\personalized\x07vatar.png', null=True, upload_to=member.models.upload_image_path),
        ),
    ]
