# Generated by Django 4.1.2 on 2022-12-09 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0003_alter_membersubgroup_subgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationInformation',
            fields=[
                ('school', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('course', models.CharField(blank=True, max_length=255, null=True)),
                ('start_year', models.PositiveIntegerField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Member.member')),
            ],
        ),
    ]
