# Generated by Django 4.0.5 on 2022-12-16 04:56

from django.db import migrations, models
import member.models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_alter_membership_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=member.models.upload_image_path),
        ),
    ]
