# Generated by Django 4.0.5 on 2022-12-16 05:11

from django.db import migrations, models
import member.models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_alter_membership_picture_alter_membership_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='picture',
            field=models.ImageField(blank=True, default='static\\images\x07vatar01.png', null=True, upload_to=member.models.upload_image_path),
        ),
        migrations.AlterField(
            model_name='membership',
            name='signature',
            field=models.ImageField(blank=True, default='static\\images\\card-img-3.jpg', null=True, upload_to=member.models.upload_image_path),
        ),
    ]
