# Generated by Django 4.0.5 on 2022-12-21 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_alter_membership_picture_alter_membership_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
