# Generated by Django 4.0.5 on 2022-12-21 23:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_alter_membership_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
