# Generated by Django 4.0.5 on 2023-01-01 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_membership_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='members',
            field=models.ManyToManyField(through='member.MemberCommittee', to='member.membership'),
        ),
        migrations.AddField(
            model_name='subgroup',
            name='members',
            field=models.ManyToManyField(through='member.MemberSubGroup', to='member.membership'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='date_of_birth',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='marital_status',
            field=models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed'), ('SP', 'Single_Parent')], default='S', max_length=2),
        ),
        migrations.AlterField(
            model_name='membership',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Spouse Name (Type Nill if Single)'),
        ),
        migrations.AlterField(
            model_name='membersubgroup',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.membership'),
        ),
        migrations.AlterField(
            model_name='membersubgroup',
            name='subgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.subgroup'),
        ),
    ]
