# Generated by Django 4.1.2 on 2022-12-13 04:04

from django.db import migrations, models
import frontend.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Church_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_name', models.CharField(blank=True, max_length=255, null=True)),
                ('church_address', models.CharField(blank=True, max_length=255, null=True)),
                ('church_logo', models.ImageField(blank=True, null=True, upload_to=frontend.models.upload_image_path)),
                ('church_domain', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
