# Generated by Django 4.1.2 on 2022-12-13 05:18

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='church_info',
            options={'verbose_name_plural': 'Church Info'},
        ),
        migrations.AddField(
            model_name='church_info',
            name='church_contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='church_info',
            name='church_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='church_info',
            name='church_domain',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
