# Generated by Django 4.1.2 on 2022-10-24 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shepherd',
            new_name='Discipler',
        ),
        migrations.RenameModel(
            old_name='Ministry',
            new_name='Sub_Group',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='shepherd',
            new_name='discipler',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='ministry',
            new_name='sub_Group',
        ),
    ]
