# Generated by Django 4.1.2 on 2022-10-24 14:06

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_department_member_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='location',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
