# Generated by Django 4.1.2 on 2022-10-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_member_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='name',
        ),
        migrations.AddField(
            model_name='member',
            name='first_name',
            field=models.CharField(default=1, max_length=255, verbose_name='First Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='last_name',
            field=models.CharField(default=1, max_length=255, verbose_name='Last Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='other_names',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Other Names'),
        ),
    ]
