# Generated by Django 4.1.2 on 2022-10-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_remove_member_location_member_address_member_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
