# Generated by Django 4.1.2 on 2022-10-24 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_relationship_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='relationship_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='Relationship_Statis', to='members.relationship_status'),
            preserve_default=False,
        ),
    ]
