# Generated by Django 4.1.2 on 2022-10-24 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_member_relationship_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='relationship_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Relationship_Status', to='members.relationship_status'),
        ),
    ]
