# Generated by Django 4.1.2 on 2022-10-24 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_member_relationship_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='relationship_status',
        ),
        migrations.DeleteModel(
            name='Relationship_status',
        ),
    ]
