# Generated by Django 4.1.2 on 2022-10-24 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_remove_member_relationship_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='relationship_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='MEDIA_CHOICES', to='members.relationship_status'),
            preserve_default=False,
        ),
    ]
