# Generated by Django 4.1.2 on 2022-10-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_applicant_member_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='sub_Group',
            new_name='sub_group',
        ),
        migrations.RemoveField(
            model_name='member',
            name='status',
        ),
        migrations.AlterField(
            model_name='member',
            name='lga',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Local Governemnt Area'),
        ),
        migrations.DeleteModel(
            name='Applicant',
        ),
    ]
