# Generated by Django 4.1.2 on 2022-10-24 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_rename_sub_group_member_sub_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marital_status', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced')], default='S', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='relationship_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.relationship_status'),
        ),
    ]
