# Generated by Django 4.1.2 on 2022-10-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_relationship_status_member_relationship_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='relationship_status',
        ),
        migrations.AddField(
            model_name='member',
            name='marital_status',
            field=models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced')], default='S', max_length=1),
        ),
        migrations.DeleteModel(
            name='Relationship_Status',
        ),
    ]
